[owner]
ids = []
reduce_cooldowns = false 
reduce_cooldowns_blacklist = [] 
bypass_cooldowns = false 
bypass_cooldowns_blacklist = [] 

[prefixes]
list = [] 
mention_prefix = true 
role_mention_prefix = true 

[general.cooldown]
on_cooldown_error = "Woah! You're using that command too quickly."
on_cooldown_error_description = "You can run this command again in **$time$** second(s)!"

[emojis]
success = "<:success:869103772952059934>"
warn = "<:error:869103848369827880>"
error = "<:error:869103848369827880>"

[colors]
main = "#2ecc71"
warn = "#addb67"
error = "#ef5350"

[colors.logging]
join = "#2ecc71"
leave = "#2ecc71"
success = "#2ecc71"
info = "#82aaff"
warning = "#addb67"
error = "#ef5350"
debug = "#f78c6c"
shard_success = "#2ecc71"
shard_info = "#82aaff"
shard_warning = "#addb67"
shard_error = "#ef5350"

[logging.local]
guild_join = false 
guild_leave = false 
success = true 
info = true
warning = true
error = true
debug = true
shard_success = true
shard_info = true
shard_warning = true
shard_error = true

[logging.webhook]
guild_join = false 
guild_leave = false
success = false 
info = false 
warning = false 
error = false 
debug = false 
shard_success = false 
shard_info = false
shard_warning = false
shard_error = false